spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
db:
  database: sky_product
meilisearch:
  host-url: http://localhost:7700
  enabled: true