spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
db:
  database: sky_user
sky:
  jwt:
    user-secret-key: itcast
    user-ttl: 7200000
    user-token-name: authentication