spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
db:
  database: sky_admin_operation
sky:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 7200000
    admin-token-name: token
  minio:
    endpoint: {host}
    access-key: {access-key}
    secret-key: {secret-key}
    bucket-name: {bucket-name}